# Generated by Django 4.0.3 on 2022-04-23 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_user_following'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_published']},
        ),
    ]
